[project]
name = "xiaomusic"
version = "0.1.87"
description = "Play Music with xiaomi AI speaker"
authors = [
    {name = "涵曦", email = "im.hanxi@gmail.com"},
]
dependencies = [
    "requests==2.31.0",
    "aiohttp>=3.8.6",
    "miservice-fork>=2.5.0",
    "mutagen>=1.47.0",
    "yt-dlp>=2024.04.09",
    "flask[async]>=3.0.1",
    "waitress>=3.0.0",
    "flask-HTTPAuth>=4.8.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/hanxi/xiaomusic"

[project.scripts]
xiaomusic = "xiaomusic.cli:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
[tool.pdm.dev-dependencies]
lint = [
    "ruff>=0.4.8",
]
[tool.ruff]
lint.select = [
        "B", # flake8-bugbear
        "C4", # flake8-comprehensions
        "E", # pycodestyle - Error
        "F", # Pyflakes
        "I", # isort
        "W", # pycodestyle - Warning
        "UP", # pyupgrade
]
lint.ignore = [
        "E501", # line-too-long
        "W191", # tab-indentation
]
include = ["**/*.py", "**/*.pyi", "**/pyproject.toml"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pdm.scripts]
lint = "ruff check ."
fmt = "ruff format ."
